language: python
python:
  - 2.6
  - 2.7
  - 3.0

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - sudo /usr/bin/yes | apt-get install python-numpy python-scipy python-mysqldb python-lxml
  - sudo /usr/bin/yes | apt-get install python-qt4
  - sudo /usr/bin/yes | apt-get autoremove
  - sudo /usr/bin/yes | apt-get autoclean
  - sudo /usr/bin/yes | apt-get install python-numpy python-scipy python-mysqldb python-lxml
  - sudo /usr/bin/yes | apt-get install python-qt4
  - /usr/bin/yes | sudo python setup.py install

before_script:

  - python -c 'from PyQt4 import QtCore, QtGui; print dir(QtGui)'
  - python -c 'import PyQt4; print PyQt4.__file__'

# command to run tests, e.g. python setup.py test
script:  python test.py

branches:
  only:
    - master
