language: python
python:
  - 2.6
  - 2.7
  - 3.0

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - sudo apt-get install python-qt4 python-numpy python-scipy python-mysqldb python-lxml
  - yes | sudo python setup.py install

# command to run tests, e.g. python setup.py test
script:  python test.py

branches:
  only:
    - master
