language: python
python:
  - 2.6
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install python-qt python-numpy python-scipy python-mysqldb python-lxml
# command to run tests, e.g. python setup.py test
script:  python test.py
